#############################################################################
# Makefile for building: Synthetizer
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  Synthetizer.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile Synthetizer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -DQT_FATAL_WARNINGS=1 -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I. -Isrc -isystem /usr/include/libgig -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Synthetizer1.0.0
DISTDIR = /home/ray/projects/audio/synthesis/.tmp/Synthetizer1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/usr/lib/libgig -lgig -L/usr/lib/python2.7 -lpython2.7 -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/horizontallevelbar.cpp \
		src/verticallevelbar.cpp \
		src/splitbankform.cpp \
		src/favoriteform.cpp \
		src/usbform.cpp \
		src/effectsform.cpp \
		src/categoriesform.cpp \
		src/presetbankform.cpp \
		src/displayform.cpp \
		src/systeminfoform.cpp \
		src/mainsystemform.cpp \
		src/multisamplesform.cpp \
		src/soundbankform.cpp \
		src/doublesidedverticalbar.cpp \
		src/frontbuttoneditform.cpp \
		src/soundsplitform.cpp \
		src/piano.cpp \
		src/effectseditform.cpp \
		src/ampsettingsform.cpp \
		src/filtersettingsform.cpp \
		src/pitchsettingsform.cpp \
		src/adsrgraph.cpp \
		src/soundeditform.cpp \
		src/miscsettingsform.cpp \
		src/effectsroutingform.cpp \
		src/sampleeffectlink.cpp \
		src/effecteffectlink.cpp \
		src/mastereffectlink.cpp \
		effectswidget.cpp \
		effectroutinglink.cpp \
		src/gigfile.cpp qrc_res.cpp \
		moc_mainwindow.cpp \
		moc_horizontallevelbar.cpp \
		moc_verticallevelbar.cpp \
		moc_splitbankform.cpp \
		moc_favoriteform.cpp \
		moc_usbform.cpp \
		moc_effectsform.cpp \
		moc_categoriesform.cpp \
		moc_presetbankform.cpp \
		moc_displayform.cpp \
		moc_systeminfoform.cpp \
		moc_mainsystemform.cpp \
		moc_multisamplesform.cpp \
		moc_soundbankform.cpp \
		moc_doublesidedverticalbar.cpp \
		moc_frontbuttoneditform.cpp \
		moc_soundsplitform.cpp \
		moc_piano.cpp \
		moc_effectseditform.cpp \
		moc_ampsettingsform.cpp \
		moc_filtersettingsform.cpp \
		moc_pitchsettingsform.cpp \
		moc_soundeditform.cpp \
		moc_miscsettingsform.cpp \
		moc_effectsroutingform.cpp \
		moc_effectswidget.cpp \
		moc_gigfile.cpp
OBJECTS       = main.o \
		mainwindow.o \
		horizontallevelbar.o \
		verticallevelbar.o \
		splitbankform.o \
		favoriteform.o \
		usbform.o \
		effectsform.o \
		categoriesform.o \
		presetbankform.o \
		displayform.o \
		systeminfoform.o \
		mainsystemform.o \
		multisamplesform.o \
		soundbankform.o \
		doublesidedverticalbar.o \
		frontbuttoneditform.o \
		soundsplitform.o \
		piano.o \
		effectseditform.o \
		ampsettingsform.o \
		filtersettingsform.o \
		pitchsettingsform.o \
		adsrgraph.o \
		soundeditform.o \
		miscsettingsform.o \
		effectsroutingform.o \
		sampleeffectlink.o \
		effecteffectlink.o \
		mastereffectlink.o \
		effectswidget.o \
		effectroutinglink.o \
		gigfile.o \
		qrc_res.o \
		moc_mainwindow.o \
		moc_horizontallevelbar.o \
		moc_verticallevelbar.o \
		moc_splitbankform.o \
		moc_favoriteform.o \
		moc_usbform.o \
		moc_effectsform.o \
		moc_categoriesform.o \
		moc_presetbankform.o \
		moc_displayform.o \
		moc_systeminfoform.o \
		moc_mainsystemform.o \
		moc_multisamplesform.o \
		moc_soundbankform.o \
		moc_doublesidedverticalbar.o \
		moc_frontbuttoneditform.o \
		moc_soundsplitform.o \
		moc_piano.o \
		moc_effectseditform.o \
		moc_ampsettingsform.o \
		moc_filtersettingsform.o \
		moc_pitchsettingsform.o \
		moc_soundeditform.o \
		moc_miscsettingsform.o \
		moc_effectsroutingform.o \
		moc_effectswidget.o \
		moc_gigfile.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Synthetizer.pro src/mainwindow.h \
		src/horizontallevelbar.h \
		src/verticallevelbar.h \
		src/splitbankform.h \
		src/favoriteform.h \
		src/usbform.h \
		src/effectsform.h \
		src/categoriesform.h \
		src/presetbankform.h \
		src/displayform.h \
		src/systeminfoform.h \
		src/mainsystemform.h \
		src/multisamplesform.h \
		src/soundbankform.h \
		src/doublesidedverticalbar.h \
		src/frontbuttoneditform.h \
		src/soundsplitform.h \
		src/piano.h \
		src/effectseditform.h \
		src/ampsettingsform.h \
		src/filtersettingsform.h \
		src/pitchsettingsform.h \
		src/adsrgraph.h \
		src/soundeditform.h \
		src/miscsettingsform.h \
		src/effectsroutingform.h \
		src/sampleeffectlink.h \
		src/effecteffectlink.h \
		src/mastereffectlink.h \
		effectswidget.h \
		effectroutinglink.h \
		src/gigfile.h src/main.cpp \
		src/mainwindow.cpp \
		src/horizontallevelbar.cpp \
		src/verticallevelbar.cpp \
		src/splitbankform.cpp \
		src/favoriteform.cpp \
		src/usbform.cpp \
		src/effectsform.cpp \
		src/categoriesform.cpp \
		src/presetbankform.cpp \
		src/displayform.cpp \
		src/systeminfoform.cpp \
		src/mainsystemform.cpp \
		src/multisamplesform.cpp \
		src/soundbankform.cpp \
		src/doublesidedverticalbar.cpp \
		src/frontbuttoneditform.cpp \
		src/soundsplitform.cpp \
		src/piano.cpp \
		src/effectseditform.cpp \
		src/ampsettingsform.cpp \
		src/filtersettingsform.cpp \
		src/pitchsettingsform.cpp \
		src/adsrgraph.cpp \
		src/soundeditform.cpp \
		src/miscsettingsform.cpp \
		src/effectsroutingform.cpp \
		src/sampleeffectlink.cpp \
		src/effecteffectlink.cpp \
		src/mastereffectlink.cpp \
		effectswidget.cpp \
		effectroutinglink.cpp \
		src/gigfile.cpp
QMAKE_TARGET  = Synthetizer
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Synthetizer


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h ui_splitbankform.h ui_favoriteform.h ui_usbform.h ui_effectsform.h ui_categoriesform.h ui_presetbankform.h ui_displayform.h ui_systeminfoform.h ui_mainsystemform.h ui_multisamplesform.h ui_soundbankform.h ui_frontbuttoneditform.h ui_soundsplitform.h ui_effectseditform.h ui_ampsettingsform.h ui_filtersettingsform.h ui_pitchsettingsform.h ui_soundeditform.h ui_miscsettingsform.h ui_effectsroutingform.h ui_effectswidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Synthetizer.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Synthetizer.pro \
		res/res.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl
	$(QMAKE) -o Makefile Synthetizer.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Synthetizer.pro:
res/res.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Synthetizer.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res/res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/mainwindow.h src/horizontallevelbar.h src/verticallevelbar.h src/splitbankform.h src/favoriteform.h src/usbform.h src/effectsform.h src/categoriesform.h src/presetbankform.h src/displayform.h src/systeminfoform.h src/mainsystemform.h src/multisamplesform.h src/soundbankform.h src/doublesidedverticalbar.h src/frontbuttoneditform.h src/soundsplitform.h src/piano.h src/effectseditform.h src/ampsettingsform.h src/filtersettingsform.h src/pitchsettingsform.h src/adsrgraph.h src/soundeditform.h src/miscsettingsform.h src/effectsroutingform.h src/sampleeffectlink.h src/effecteffectlink.h src/mastereffectlink.h effectswidget.h effectroutinglink.h src/gigfile.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/horizontallevelbar.cpp src/verticallevelbar.cpp src/splitbankform.cpp src/favoriteform.cpp src/usbform.cpp src/effectsform.cpp src/categoriesform.cpp src/presetbankform.cpp src/displayform.cpp src/systeminfoform.cpp src/mainsystemform.cpp src/multisamplesform.cpp src/soundbankform.cpp src/doublesidedverticalbar.cpp src/frontbuttoneditform.cpp src/soundsplitform.cpp src/piano.cpp src/effectseditform.cpp src/ampsettingsform.cpp src/filtersettingsform.cpp src/pitchsettingsform.cpp src/adsrgraph.cpp src/soundeditform.cpp src/miscsettingsform.cpp src/effectsroutingform.cpp src/sampleeffectlink.cpp src/effecteffectlink.cpp src/mastereffectlink.cpp effectswidget.cpp effectroutinglink.cpp src/gigfile.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.ui ui/splitbankform.ui ui/favoriteform.ui ui/usbform.ui ui/effectsform.ui ui/categoriesform.ui ui/presetbankform.ui ui/displayform.ui ui/systeminfoform.ui ui/mainsystemform.ui ui/multisamplesform.ui ui/soundbankform.ui ui/frontbuttoneditform.ui ui/soundsplitform.ui ui/effectseditform.ui ui/ampsettingsform.ui ui/filtersettingsform.ui ui/pitchsettingsform.ui ui/soundeditform.ui ui/miscsettingsform.ui ui/effectsroutingform.ui effectswidget.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res/res.qrc \
		res/images/Envelope.jpg \
		res/qss/tablewidgetdefaultlong.qss \
		res/qss/buttonSample.qss \
		res/qss/tablewidgetcb.qss \
		res/qss/tablewidgetdefault.qss \
		res/qss/stylesheet.qss \
		res/qss/buttons.qss \
		res/font/OpenSans/OpenSans-Light.ttf \
		res/font/OpenSans/OpenSans-Italic.ttf \
		res/font/OpenSans/OpenSans-LightItalic.ttf \
		res/font/OpenSans/OpenSans-ExtraBoldItalic.ttf \
		res/font/OpenSans/OpenSans-ExtraBold.ttf \
		res/font/OpenSans/OpenSans-Semibold.ttf \
		res/font/OpenSans/OpenSans-Regular.ttf \
		res/font/OpenSans/OpenSans-SemiboldItalic.ttf \
		res/font/OpenSans/OpenSans-BoldItalic.ttf \
		res/font/OpenSans/OpenSans-Bold.ttf
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name res res/res.qrc -o qrc_res.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_horizontallevelbar.cpp moc_verticallevelbar.cpp moc_splitbankform.cpp moc_favoriteform.cpp moc_usbform.cpp moc_effectsform.cpp moc_categoriesform.cpp moc_presetbankform.cpp moc_displayform.cpp moc_systeminfoform.cpp moc_mainsystemform.cpp moc_multisamplesform.cpp moc_soundbankform.cpp moc_doublesidedverticalbar.cpp moc_frontbuttoneditform.cpp moc_soundsplitform.cpp moc_piano.cpp moc_effectseditform.cpp moc_ampsettingsform.cpp moc_filtersettingsform.cpp moc_pitchsettingsform.cpp moc_soundeditform.cpp moc_miscsettingsform.cpp moc_effectsroutingform.cpp moc_effectswidget.cpp moc_gigfile.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_horizontallevelbar.cpp moc_verticallevelbar.cpp moc_splitbankform.cpp moc_favoriteform.cpp moc_usbform.cpp moc_effectsform.cpp moc_categoriesform.cpp moc_presetbankform.cpp moc_displayform.cpp moc_systeminfoform.cpp moc_mainsystemform.cpp moc_multisamplesform.cpp moc_soundbankform.cpp moc_doublesidedverticalbar.cpp moc_frontbuttoneditform.cpp moc_soundsplitform.cpp moc_piano.cpp moc_effectseditform.cpp moc_ampsettingsform.cpp moc_filtersettingsform.cpp moc_pitchsettingsform.cpp moc_soundeditform.cpp moc_miscsettingsform.cpp moc_effectsroutingform.cpp moc_effectswidget.cpp moc_gigfile.cpp
moc_mainwindow.cpp: src/presetbankform.h \
		src/adsrgraph.h \
		src/splitbankform.h \
		src/favoriteform.h \
		src/frontbuttoneditform.h \
		src/usbform.h \
		src/categoriesform.h \
		src/effectsform.h \
		src/multisamplesform.h \
		src/soundbankform.h \
		src/soundsplitform.h \
		src/effectseditform.h \
		src/soundeditform.h \
		src/ampsettingsform.h \
		src/filtersettingsform.h \
		src/pitchsettingsform.h \
		src/miscsettingsform.h \
		src/effectsroutingform.h \
		effectswidget.h \
		effectroutinglink.h \
		src/gigfile.h \
		src/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainwindow.h -o moc_mainwindow.cpp

moc_horizontallevelbar.cpp: src/horizontallevelbar.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/horizontallevelbar.h -o moc_horizontallevelbar.cpp

moc_verticallevelbar.cpp: src/verticallevelbar.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/verticallevelbar.h -o moc_verticallevelbar.cpp

moc_splitbankform.cpp: src/splitbankform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/splitbankform.h -o moc_splitbankform.cpp

moc_favoriteform.cpp: src/favoriteform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/favoriteform.h -o moc_favoriteform.cpp

moc_usbform.cpp: src/usbform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/usbform.h -o moc_usbform.cpp

moc_effectsform.cpp: src/effectsform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/effectsform.h -o moc_effectsform.cpp

moc_categoriesform.cpp: src/categoriesform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/categoriesform.h -o moc_categoriesform.cpp

moc_presetbankform.cpp: src/adsrgraph.h \
		src/presetbankform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/presetbankform.h -o moc_presetbankform.cpp

moc_displayform.cpp: src/displayform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/displayform.h -o moc_displayform.cpp

moc_systeminfoform.cpp: src/systeminfoform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/systeminfoform.h -o moc_systeminfoform.cpp

moc_mainsystemform.cpp: src/mainsystemform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainsystemform.h -o moc_mainsystemform.cpp

moc_multisamplesform.cpp: src/multisamplesform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/multisamplesform.h -o moc_multisamplesform.cpp

moc_soundbankform.cpp: src/soundbankform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/soundbankform.h -o moc_soundbankform.cpp

moc_doublesidedverticalbar.cpp: src/doublesidedverticalbar.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/doublesidedverticalbar.h -o moc_doublesidedverticalbar.cpp

moc_frontbuttoneditform.cpp: src/frontbuttoneditform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/frontbuttoneditform.h -o moc_frontbuttoneditform.cpp

moc_soundsplitform.cpp: src/soundsplitform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/soundsplitform.h -o moc_soundsplitform.cpp

moc_piano.cpp: src/piano.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/piano.h -o moc_piano.cpp

moc_effectseditform.cpp: src/effectseditform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/effectseditform.h -o moc_effectseditform.cpp

moc_ampsettingsform.cpp: src/ampsettingsform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/ampsettingsform.h -o moc_ampsettingsform.cpp

moc_filtersettingsform.cpp: src/filtersettingsform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/filtersettingsform.h -o moc_filtersettingsform.cpp

moc_pitchsettingsform.cpp: src/pitchsettingsform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/pitchsettingsform.h -o moc_pitchsettingsform.cpp

moc_soundeditform.cpp: src/ampsettingsform.h \
		src/filtersettingsform.h \
		src/pitchsettingsform.h \
		src/miscsettingsform.h \
		src/soundeditform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/soundeditform.h -o moc_soundeditform.cpp

moc_miscsettingsform.cpp: src/miscsettingsform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/miscsettingsform.h -o moc_miscsettingsform.cpp

moc_effectsroutingform.cpp: effectswidget.h \
		effectroutinglink.h \
		src/effectsroutingform.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/effectsroutingform.h -o moc_effectsroutingform.cpp

moc_effectswidget.cpp: effectswidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include effectswidget.h -o moc_effectswidget.cpp

moc_gigfile.cpp: src/gigfile.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/ray/projects/audio/synthesis -I/home/ray/projects/audio/synthesis/src -I/usr/include/libgig -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/gigfile.h -o moc_gigfile.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_splitbankform.h ui_favoriteform.h ui_usbform.h ui_effectsform.h ui_categoriesform.h ui_presetbankform.h ui_displayform.h ui_systeminfoform.h ui_mainsystemform.h ui_multisamplesform.h ui_soundbankform.h ui_frontbuttoneditform.h ui_soundsplitform.h ui_effectseditform.h ui_ampsettingsform.h ui_filtersettingsform.h ui_pitchsettingsform.h ui_soundeditform.h ui_miscsettingsform.h ui_effectsroutingform.h ui_effectswidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_splitbankform.h ui_favoriteform.h ui_usbform.h ui_effectsform.h ui_categoriesform.h ui_presetbankform.h ui_displayform.h ui_systeminfoform.h ui_mainsystemform.h ui_multisamplesform.h ui_soundbankform.h ui_frontbuttoneditform.h ui_soundsplitform.h ui_effectseditform.h ui_ampsettingsform.h ui_filtersettingsform.h ui_pitchsettingsform.h ui_soundeditform.h ui_miscsettingsform.h ui_effectsroutingform.h ui_effectswidget.h
ui_mainwindow.h: ui/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

ui_splitbankform.h: ui/splitbankform.ui \
		src/verticallevelbar.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/splitbankform.ui -o ui_splitbankform.h

ui_favoriteform.h: ui/favoriteform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/favoriteform.ui -o ui_favoriteform.h

ui_usbform.h: ui/usbform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/usbform.ui -o ui_usbform.h

ui_effectsform.h: ui/effectsform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/effectsform.ui -o ui_effectsform.h

ui_categoriesform.h: ui/categoriesform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/categoriesform.ui -o ui_categoriesform.h

ui_presetbankform.h: ui/presetbankform.ui \
		src/doublesidedverticalbar.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/presetbankform.ui -o ui_presetbankform.h

ui_displayform.h: ui/displayform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/displayform.ui -o ui_displayform.h

ui_systeminfoform.h: ui/systeminfoform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/systeminfoform.ui -o ui_systeminfoform.h

ui_mainsystemform.h: ui/mainsystemform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/mainsystemform.ui -o ui_mainsystemform.h

ui_multisamplesform.h: ui/multisamplesform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/multisamplesform.ui -o ui_multisamplesform.h

ui_soundbankform.h: ui/soundbankform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/soundbankform.ui -o ui_soundbankform.h

ui_frontbuttoneditform.h: ui/frontbuttoneditform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/frontbuttoneditform.ui -o ui_frontbuttoneditform.h

ui_soundsplitform.h: ui/soundsplitform.ui \
		src/piano.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/soundsplitform.ui -o ui_soundsplitform.h

ui_effectseditform.h: ui/effectseditform.ui \
		src/verticallevelbar.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/effectseditform.ui -o ui_effectseditform.h

ui_ampsettingsform.h: ui/ampsettingsform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/ampsettingsform.ui -o ui_ampsettingsform.h

ui_filtersettingsform.h: ui/filtersettingsform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/filtersettingsform.ui -o ui_filtersettingsform.h

ui_pitchsettingsform.h: ui/pitchsettingsform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/pitchsettingsform.ui -o ui_pitchsettingsform.h

ui_soundeditform.h: ui/soundeditform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/soundeditform.ui -o ui_soundeditform.h

ui_miscsettingsform.h: ui/miscsettingsform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/miscsettingsform.ui -o ui_miscsettingsform.h

ui_effectsroutingform.h: ui/effectsroutingform.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/effectsroutingform.ui -o ui_effectsroutingform.h

ui_effectswidget.h: effectswidget.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic effectswidget.ui -o ui_effectswidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/mainwindow.h \
		src/presetbankform.h \
		src/adsrgraph.h \
		src/splitbankform.h \
		src/favoriteform.h \
		src/frontbuttoneditform.h \
		src/usbform.h \
		src/categoriesform.h \
		src/effectsform.h \
		src/multisamplesform.h \
		src/soundbankform.h \
		src/soundsplitform.h \
		src/effectseditform.h \
		src/soundeditform.h \
		src/ampsettingsform.h \
		src/filtersettingsform.h \
		src/pitchsettingsform.h \
		src/miscsettingsform.h \
		src/effectsroutingform.h \
		effectswidget.h \
		effectroutinglink.h \
		src/gigfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/presetbankform.h \
		src/adsrgraph.h \
		src/splitbankform.h \
		src/favoriteform.h \
		src/frontbuttoneditform.h \
		src/usbform.h \
		src/categoriesform.h \
		src/effectsform.h \
		src/multisamplesform.h \
		src/soundbankform.h \
		src/soundsplitform.h \
		src/effectseditform.h \
		src/soundeditform.h \
		src/ampsettingsform.h \
		src/filtersettingsform.h \
		src/pitchsettingsform.h \
		src/miscsettingsform.h \
		src/effectsroutingform.h \
		effectswidget.h \
		effectroutinglink.h \
		src/gigfile.h \
		ui_mainwindow.h \
		ui_presetbankform.h \
		src/doublesidedverticalbar.h \
		ui_splitbankform.h \
		src/verticallevelbar.h \
		ui_favoriteform.h \
		ui_frontbuttoneditform.h \
		ui_soundsplitform.h \
		src/piano.h \
		ui_effectseditform.h \
		ui_effectsform.h \
		ui_soundbankform.h \
		ui_multisamplesform.h \
		ui_categoriesform.h \
		ui_effectsroutingform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

horizontallevelbar.o: src/horizontallevelbar.cpp src/horizontallevelbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o horizontallevelbar.o src/horizontallevelbar.cpp

verticallevelbar.o: src/verticallevelbar.cpp src/verticallevelbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o verticallevelbar.o src/verticallevelbar.cpp

splitbankform.o: src/splitbankform.cpp src/splitbankform.h \
		ui_splitbankform.h \
		src/verticallevelbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o splitbankform.o src/splitbankform.cpp

favoriteform.o: src/favoriteform.cpp src/favoriteform.h \
		ui_favoriteform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o favoriteform.o src/favoriteform.cpp

usbform.o: src/usbform.cpp src/usbform.h \
		ui_usbform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o usbform.o src/usbform.cpp

effectsform.o: src/effectsform.cpp src/effectsform.h \
		ui_effectsform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o effectsform.o src/effectsform.cpp

categoriesform.o: src/categoriesform.cpp src/categoriesform.h \
		ui_categoriesform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o categoriesform.o src/categoriesform.cpp

presetbankform.o: src/presetbankform.cpp src/presetbankform.h \
		src/adsrgraph.h \
		ui_presetbankform.h \
		src/doublesidedverticalbar.h \
		src/gigfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o presetbankform.o src/presetbankform.cpp

displayform.o: src/displayform.cpp src/displayform.h \
		ui_displayform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o displayform.o src/displayform.cpp

systeminfoform.o: src/systeminfoform.cpp src/systeminfoform.h \
		ui_systeminfoform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systeminfoform.o src/systeminfoform.cpp

mainsystemform.o: src/mainsystemform.cpp src/mainsystemform.h \
		ui_mainsystemform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainsystemform.o src/mainsystemform.cpp

multisamplesform.o: src/multisamplesform.cpp src/multisamplesform.h \
		ui_multisamplesform.h \
		src/gigfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multisamplesform.o src/multisamplesform.cpp

soundbankform.o: src/soundbankform.cpp src/soundbankform.h \
		ui_soundbankform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundbankform.o src/soundbankform.cpp

doublesidedverticalbar.o: src/doublesidedverticalbar.cpp src/doublesidedverticalbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublesidedverticalbar.o src/doublesidedverticalbar.cpp

frontbuttoneditform.o: src/frontbuttoneditform.cpp src/frontbuttoneditform.h \
		ui_frontbuttoneditform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frontbuttoneditform.o src/frontbuttoneditform.cpp

soundsplitform.o: src/soundsplitform.cpp src/soundsplitform.h \
		ui_soundsplitform.h \
		src/piano.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundsplitform.o src/soundsplitform.cpp

piano.o: src/piano.cpp src/piano.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o piano.o src/piano.cpp

effectseditform.o: src/effectseditform.cpp src/effectseditform.h \
		ui_effectseditform.h \
		src/verticallevelbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o effectseditform.o src/effectseditform.cpp

ampsettingsform.o: src/ampsettingsform.cpp src/ampsettingsform.h \
		ui_ampsettingsform.h \
		src/gigfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ampsettingsform.o src/ampsettingsform.cpp

filtersettingsform.o: src/filtersettingsform.cpp src/filtersettingsform.h \
		ui_filtersettingsform.h \
		src/gigfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filtersettingsform.o src/filtersettingsform.cpp

pitchsettingsform.o: src/pitchsettingsform.cpp src/pitchsettingsform.h \
		ui_pitchsettingsform.h \
		src/gigfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pitchsettingsform.o src/pitchsettingsform.cpp

adsrgraph.o: src/adsrgraph.cpp src/adsrgraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adsrgraph.o src/adsrgraph.cpp

soundeditform.o: src/soundeditform.cpp src/soundeditform.h \
		src/ampsettingsform.h \
		src/filtersettingsform.h \
		src/pitchsettingsform.h \
		src/miscsettingsform.h \
		ui_soundeditform.h \
		src/gigfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundeditform.o src/soundeditform.cpp

miscsettingsform.o: src/miscsettingsform.cpp src/miscsettingsform.h \
		ui_miscsettingsform.h \
		src/gigfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o miscsettingsform.o src/miscsettingsform.cpp

effectsroutingform.o: src/effectsroutingform.cpp src/effectsroutingform.h \
		effectswidget.h \
		effectroutinglink.h \
		ui_effectsroutingform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o effectsroutingform.o src/effectsroutingform.cpp

sampleeffectlink.o: src/sampleeffectlink.cpp src/sampleeffectlink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sampleeffectlink.o src/sampleeffectlink.cpp

effecteffectlink.o: src/effecteffectlink.cpp src/effecteffectlink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o effecteffectlink.o src/effecteffectlink.cpp

mastereffectlink.o: src/mastereffectlink.cpp src/mastereffectlink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mastereffectlink.o src/mastereffectlink.cpp

effectswidget.o: effectswidget.cpp effectswidget.h \
		ui_effectswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o effectswidget.o effectswidget.cpp

effectroutinglink.o: effectroutinglink.cpp effectroutinglink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o effectroutinglink.o effectroutinglink.cpp

gigfile.o: src/gigfile.cpp src/gigfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gigfile.o src/gigfile.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_horizontallevelbar.o: moc_horizontallevelbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_horizontallevelbar.o moc_horizontallevelbar.cpp

moc_verticallevelbar.o: moc_verticallevelbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_verticallevelbar.o moc_verticallevelbar.cpp

moc_splitbankform.o: moc_splitbankform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_splitbankform.o moc_splitbankform.cpp

moc_favoriteform.o: moc_favoriteform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_favoriteform.o moc_favoriteform.cpp

moc_usbform.o: moc_usbform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_usbform.o moc_usbform.cpp

moc_effectsform.o: moc_effectsform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_effectsform.o moc_effectsform.cpp

moc_categoriesform.o: moc_categoriesform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_categoriesform.o moc_categoriesform.cpp

moc_presetbankform.o: moc_presetbankform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_presetbankform.o moc_presetbankform.cpp

moc_displayform.o: moc_displayform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_displayform.o moc_displayform.cpp

moc_systeminfoform.o: moc_systeminfoform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systeminfoform.o moc_systeminfoform.cpp

moc_mainsystemform.o: moc_mainsystemform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainsystemform.o moc_mainsystemform.cpp

moc_multisamplesform.o: moc_multisamplesform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_multisamplesform.o moc_multisamplesform.cpp

moc_soundbankform.o: moc_soundbankform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundbankform.o moc_soundbankform.cpp

moc_doublesidedverticalbar.o: moc_doublesidedverticalbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_doublesidedverticalbar.o moc_doublesidedverticalbar.cpp

moc_frontbuttoneditform.o: moc_frontbuttoneditform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frontbuttoneditform.o moc_frontbuttoneditform.cpp

moc_soundsplitform.o: moc_soundsplitform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundsplitform.o moc_soundsplitform.cpp

moc_piano.o: moc_piano.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_piano.o moc_piano.cpp

moc_effectseditform.o: moc_effectseditform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_effectseditform.o moc_effectseditform.cpp

moc_ampsettingsform.o: moc_ampsettingsform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ampsettingsform.o moc_ampsettingsform.cpp

moc_filtersettingsform.o: moc_filtersettingsform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filtersettingsform.o moc_filtersettingsform.cpp

moc_pitchsettingsform.o: moc_pitchsettingsform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pitchsettingsform.o moc_pitchsettingsform.cpp

moc_soundeditform.o: moc_soundeditform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundeditform.o moc_soundeditform.cpp

moc_miscsettingsform.o: moc_miscsettingsform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_miscsettingsform.o moc_miscsettingsform.cpp

moc_effectsroutingform.o: moc_effectsroutingform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_effectsroutingform.o moc_effectsroutingform.cpp

moc_effectswidget.o: moc_effectswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_effectswidget.o moc_effectswidget.cpp

moc_gigfile.o: moc_gigfile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gigfile.o moc_gigfile.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

